name: build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.adoc'
      - 'docs/**'
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:

  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      BUILD_VERSION: ${{ env.BUILD_VERSION }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: extract version
        run: |
          version=`head -n1 gradle.properties`
          echo "BUILD_VERSION=${version#projectVersion=}" >> $GITHUB_ENV
          cat $GITHUB_ENV

  read:
    name: read output
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - name: read output
        run: |
          echo ${{ needs.prepare.outputs.BUILD_VERSION }}
